# Generated by Django 5.0.2 on 2024-03-30 15:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "Customer_ID",
                    models.AutoField(max_length=5, primary_key=True, serialize=False),
                ),
                ("Customer_Type", models.CharField(default="", max_length=255)),
                (
                    "Company_Name",
                    models.CharField(default="", max_length=255, null=True),
                ),
                ("Primary_Contact_Name", models.CharField(default="", max_length=255)),
                ("Phone_Number", models.IntegerField()),
                ("Email", models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "Product_ID",
                    models.AutoField(max_length=6, primary_key=True, serialize=False),
                ),
                ("Product_Name", models.CharField(default="", max_length=255)),
                ("Date_Updated", models.DateField()),
                ("Current_Quantity", models.IntegerField()),
                ("Unit", models.CharField(max_length=255)),
                ("Acquisition_Code", models.CharField(max_length=6)),
                ("Warehouse_Location", models.CharField(max_length=255)),
                ("Supplier", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("Employee_Type", models.CharField(default="", max_length=255)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "Order_Reference_Number",
                    models.AutoField(max_length=7, primary_key=True, serialize=False),
                ),
                ("Order_Date", models.DateField()),
                ("Customer_Name", models.CharField(max_length=255)),
                ("Order_Status", models.CharField(max_length=255)),
                ("Payment_Status", models.CharField(max_length=255)),
                ("Unit_Price", models.FloatField()),
                ("Order_Quantity", models.IntegerField()),
                ("Revised_Order_Quantity", models.IntegerField()),
                ("Discount", models.IntegerField()),
                ("Amount", models.FloatField()),
                ("Total_Amount", models.FloatField()),
                ("Note", models.CharField(max_length=255)),
                (
                    "Customer_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectapp.customer",
                    ),
                ),
                (
                    "Product_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectapp.inventory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order_Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Order_Quantity", models.CharField(max_length=255)),
                (
                    "Order_Reference_Number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectapp.order",
                    ),
                ),
                (
                    "Product_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectapp.inventory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product_Price",
            fields=[
                (
                    "Product_ID",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("Discount", models.IntegerField(max_length=3)),
                (
                    "Customer_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectapp.customer",
                    ),
                ),
            ],
        ),
    ]
