# Generated by Django 5.0.2 on 2024-03-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="Employee_Type",
            field=models.CharField(default="-", max_length=255),
        ),
    ]
