# Generated by Django 5.0.2 on 2024-02-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0002_rename_company_type_customer_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Customer_Type",
            field=models.CharField(default="", max_length=255),
        ),
    ]
