# Generated by Django 5.0.2 on 2024-04-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0002_alter_account_employee_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Phone_Number",
            field=models.CharField(default="", max_length=255),
        ),
    ]
