# Generated by Django 5.0.2 on 2024-04-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0003_alter_customer_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="Unit_Price",
        ),
        migrations.AddField(
            model_name="inventory",
            name="Unit_Price",
            field=models.FloatField(default=0),
        ),
    ]
